---
title: "validation plots"
author: "Analisa Milkey"
date: "2025-07-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
setwd("")
```

Read in average species tree height files and true heights.

```{r}
nreps = __NREPS__

min <- c()

max <- c()

true <- c()

observed_means <- c()
```

Plot coverage.

```{r}
df <- data.frame(true, min, max, observed_means)

colors <- c()
for (i in 1:nreps) {
  if (true[i] >= min[i] && true[i] <= max[i]) {
    colors[i] = "green"
  }
  else {
    colors[i] = "red"
  }
}

p <- ggplot() +
  geom_point(data = df, aes(true, observed_means), color="blue", alpha = 0.5, cex=0.5) +
  geom_point(data = df, aes(true, max), color=colors, alpha=0.5) +
  geom_point(data = df, aes(true, min), color=colors, alpha=0.5) +
  geom_linerange(aes(x=true, y=observed_means, ymin=min, ymax = max),colour=colors, alpha=0.5, size=1.1) +
  geom_abline(slope = 1, intercept = 0, color="black")

p

# count true values falling within hpd bounds
counts_within_hpd <- sum(true >= min & true <= max)
counts_within_hpd

proportion_in_range <- counts_within_hpd / length(true)
proportion_in_range

# test to ensure all values have been counted
# test should equal nreps
test <- sum(observed_means >= min & observed_means <= max)
test   
```


Plot RUV analysis.

Copy ranks from program output (run python3 ruv.py). Modify breaks and qbinom probabilities based on nparticles.

```{r}
ranks <- c()

hist(ranks, breaks=c(0,2000, 4000, 6000, 8000, 10000, 12000, 14000, 16000, 18000, 20000, 22000, 24000, 26000, 28000, 30000, 32000, 34000, 36000, 38000,40000), ylim=c(0, 50))

ci_low  <- qbinom(0.025,100,.05)

ci_mean <- qbinom(0.5,100,.05)

ci_high <- qbinom(0.975,100,.05)

abline(h=ci_high, lwd=2, lty="dotted", col="navy")

abline(h=ci_mean, lwd=2, lty="solid",  col="navy")

abline(h=ci_low, lwd=2, lty="dotted", col="navy")
```

